# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d298eb617558d38eb459d29cfce4360d82e66679b79c7e9277462949e838a3592373e8851befc2ba777c9c087bd46f134344480e62e743f4fa9b9d66ccdd6160

test:
  secret_key_base: f4b4850e01daed941aad78e65e7a1dff9ce2ee3b43e47c1af55f03621858944d9220afff6b65b20eaa32b88370c708abcfd23e73327ed8273a4d47b456a39acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
